name: TextCommands
version: '${project.version}'
main: org.s1queence.plugin.TextCommands
api-version: '1.18'
depend: [S1queenceLib]
commands:
  textcommands:
    usage: /textcommands reload
    permission: tc.perms.reload
    aliases:
      - tcs
  me:
    usage: /me <text>
  do:
    usage: /do <text>
  try:
    usage: /try <text>
  foradmins:
    usage: /foradmins <msg>
    aliases:
      - fa
  trouble:
    usage: /trouble <trouble>
  anonsay:
    usage: /anonsay <msg>
    permission: tc.perms.anonsay
    aliases:
      - as
  anonsilentsay:
    usage: /anonsilentsay <player> <msg>
    permission: tc.perms.anonsay
    aliases:
      - ass